### ISSUE TITLE
With drf-yasg, I have problem with models.TextChoices

### ISSUE THREAD

**Issue by rarvolt** [oxan/djangorestframework-dataclasses#42]
# Environment
Python 3.8
```
Django==3.2.5
djangorestframework==3.12.4
djangorestframework-dataclasses==0.9
drf-yasg=1.20.0
```

# Problem
After upgrading from 0.8 to 0.9 I've got the following exception:
```
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "/.../venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/.../venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/.../venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/.../venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/.../venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/.../venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/.../venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/.../venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/generators.py", line 404, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/generators.py", line 446, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/view.py", line 45, in get_operation
    responses = self.get_responses()
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/view.py", line 182, in get_responses
    responses=self.get_response_schemas(response_serializers)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/view.py", line 269, in get_response_schemas
    schema=self.serializer_to_schema(serializer),
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 437, in serializer_to_schema
    return self.probe_inspectors(
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 33, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 124, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/openapi.py", line 688, in setdefault
    ret = maker()
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 100, in make_schema_definition
    child_schema = self.probe_field_inspectors(
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 640, in field_to_swagger_object
    choice = field_value_to_representation(field, choice)
  File "/.../venv/lib/python3.8/site-packages/drf_yasg/utils.py", line 461, in field_value_to_representation
    value = field.to_representation(value)
  File "/.../venv/lib/python3.8/site-packages/rest_framework_dataclasses/fields.py", line 37, in to_representation
    return value.value
AttributeError: 'str' object has no attribute 'value'
```

I use a subclass of models.TextChoices as a type in my model and as a type for the dataclass.

### Example

constants.py
```python
class PetType(models.TextChoices):
    CAT = 'cat', _('Cat')
    DOG = 'dog', _('Dog')
    PARROT = 'parrot', _('Parrot')
    HAMSTER = 'hamster', _('Hamster')
```

models.py
```python
class Pet(models.Model):
    name = models.CharField(max_length=30)
    type = models.CharField(max_length=7, choices=PetType.choices)
    age = models.PositiveSmallIntegerField()
```

serializers.py
```python
@dataclass
class PetData:
    name: str
    age: int
    type: PetType


class PetSerializer(DataclassSerializer):
    class Meta:
        dataclass = PetData
```

**Comment by oxan** [comment]
This might be the same issue as #40, can you try `master`?

**Comment by oxan** [comment]
Great! I'll push out a new release later tonight.
